[package]
name = "srvstat"
version = "0.0.8"
edition = "2021"

[dependencies]
anyhow = "1.0.101"
thiserror = "2.0.18"
sysinfo = "0.38.1"
paho-mqtt = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mockito = "1.7.2"
