[package]
name = "srvstat"
version = "0.0.8"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
sysinfo = "0.37.2"
paho-mqtt = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mockito = "1.7.1"
